// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReleaseMgmt.Infrastructure.Persistence;

#nullable disable

namespace ReleaseMgmt.Infrastructure.Migrations
{
    [DbContext(typeof(ReleaseDbContext))]
    [Migration("20260929104922_Triggers")]
    partial class Triggers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("ReleaseMgmt.Domain.Entities.AffectedCIs", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CiExternalId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CiName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReleaseTrainId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("AffectedCIs", (string)null);

                    b.HasAnnotation("Sqlite:UseSqlReturningClause", false);
                });

            modelBuilder.Entity("ReleaseMgmt.Domain.Entities.Attachments", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReleaseTrainId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UploadedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UploadedByUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Attachments", (string)null);

                    b.HasAnnotation("Sqlite:UseSqlReturningClause", false);
                });

            modelBuilder.Entity("ReleaseMgmt.Domain.Entities.AuditEvents", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActorUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AfterJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("BeforeJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OccurredAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReleaseTrainId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AuditEvents", (string)null);

                    b.HasAnnotation("Sqlite:UseSqlReturningClause", false);
                });

            modelBuilder.Entity("ReleaseMgmt.Domain.Entities.Baselines", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CapturedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CapturedAtGateId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CapturedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlannedReleaseDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReleaseTrainId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SnapshotJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Baselines", (string)null);

                    b.HasAnnotation("Sqlite:UseSqlReturningClause", false);
                });

            modelBuilder.Entity("ReleaseMgmt.Domain.Entities.Blockers", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("BundledProductId")
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RaisedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReleaseTrainId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResolvedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StageGateId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Blockers", (string)null);

                    b.HasAnnotation("Sqlite:UseSqlReturningClause", false);
                });

            modelBuilder.Entity("ReleaseMgmt.Domain.Entities.BundledProducts", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReleaseTrainId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VersionTag")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BundledProducts", (string)null);

                    b.HasAnnotation("Sqlite:UseSqlReturningClause", false);
                });

            modelBuilder.Entity("ReleaseMgmt.Domain.Entities.ChangeRecords", b =>
                {
                    b.Property<string>("ReleaseTrainId")
                        .HasColumnType("TEXT");

                    b.Property<string>("BackoutPlan")
                        .HasColumnType("TEXT");

                    b.Property<string>("CabDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("CommunicationPlan")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImplementationPlan")
                        .HasColumnType("TEXT");

                    b.Property<string>("Justification")
                        .HasColumnType("TEXT");

                    b.Property<string>("RiskImpactAnalysis")
                        .HasColumnType("TEXT");

                    b.Property<string>("TestPlan")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("ReleaseTrainId");

                    b.ToTable("ChangeRecords", (string)null);

                    b.HasAnnotation("Sqlite:UseSqlReturningClause", false);
                });

            modelBuilder.Entity("ReleaseMgmt.Domain.Entities.ChecklistTasks", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("BundledProductId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CompletedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastChangedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastChangedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerTeamId")
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerUserId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SequenceOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StageGateId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TaskDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ChecklistTasks", (string)null);

                    b.HasAnnotation("Sqlite:UseSqlReturningClause", false);
                });

            modelBuilder.Entity("ReleaseMgmt.Domain.Entities.CommDispatches", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CommTemplateId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DispatchedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DispatchedByUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HydratedBody")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HydratedSubject")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRehearsal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WebhookDestinationId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CommDispatches", (string)null);

                    b.HasAnnotation("Sqlite:UseSqlReturningClause", false);
                });

            modelBuilder.Entity("ReleaseMgmt.Domain.Entities.CommSchedule", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CommTemplateId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DispatchId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DueAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReleaseTrainId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SentAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("CommSchedule", (string)null);

                    b.HasAnnotation("Sqlite:UseSqlReturningClause", false);
                });

            modelBuilder.Entity("ReleaseMgmt.Domain.Entities.CommTemplateLibrary", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Audience")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MarkdownBody")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SubjectLine")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TemplateType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("CommTemplateLibrary", (string)null);

                    b.HasAnnotation("Sqlite:UseSqlReturningClause", false);
                });

            modelBuilder.Entity("ReleaseMgmt.Domain.Entities.CommTemplates", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Audience")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LibraryTemplateId")
                        .HasColumnType("TEXT");

                    b.Property<string>("MarkdownBody")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReleaseTrainId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StageGateId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubjectLine")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TemplateType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("CommTemplates", (string)null);

                    b.HasAnnotation("Sqlite:UseSqlReturningClause", false);
                });

            modelBuilder.Entity("ReleaseMgmt.Domain.Entities.ConnectorState", b =>
                {
                    b.Property<string>("SourceSystem")
                        .HasColumnType("TEXT");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ConsecutiveFailures")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastCycleCompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastCycleStartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastSuccessAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("SourceSystem");

                    b.ToTable("ConnectorState", (string)null);

                    b.HasAnnotation("Sqlite:UseSqlReturningClause", false);
                });

            modelBuilder.Entity("ReleaseMgmt.Domain.Entities.DeploymentWindows", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("EndsAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReleaseTrainId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StartsAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("DeploymentWindows", (string)null);

                    b.HasAnnotation("Sqlite:UseSqlReturningClause", false);
                });

            modelBuilder.Entity("ReleaseMgmt.Domain.Entities.ExportJobs", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Parameters")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReleaseTrainId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestedByUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Sha256")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StoragePath")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ExportJobs", (string)null);

                    b.HasAnnotation("Sqlite:UseSqlReturningClause", false);
                });

            modelBuilder.Entity("ReleaseMgmt.Domain.Entities.ExternalLinks", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExpectedStatus")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastSyncedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastSyncedStatus")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReleaseTrainId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceSystem")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SyncState")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ExternalLinks", (string)null);

                    b.HasAnnotation("Sqlite:UseSqlReturningClause", false);
                });

            modelBuilder.Entity("ReleaseMgmt.Domain.Entities.FreezeOverrides", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ApprovedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ApprovedByUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExpiresAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FreezeWindowId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReleaseTrainId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestedByUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FreezeOverrides", (string)null);

                    b.HasAnnotation("Sqlite:UseSqlReturningClause", false);
                });

            modelBuilder.Entity("ReleaseMgmt.Domain.Entities.FreezeWindows", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EndsAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductPattern")
                        .HasColumnType("TEXT");

                    b.Property<string>("StartsAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("FreezeWindows", (string)null);

                    b.HasAnnotation("Sqlite:UseSqlReturningClause", false);
                });

            modelBuilder.Entity("ReleaseMgmt.Domain.Entities.GateTransitions", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActorUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FromStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OccurredAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StageGateId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("GateTransitions", (string)null);

                    b.HasAnnotation("Sqlite:UseSqlReturningClause", false);
                });

            modelBuilder.Entity("ReleaseMgmt.Domain.Entities.GateWaivers", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ApprovedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ApprovedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestedByUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StageGateId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("GateWaivers", (string)null);

                    b.HasAnnotation("Sqlite:UseSqlReturningClause", false);
                });

            modelBuilder.Entity("ReleaseMgmt.Domain.Entities.GoNoGoConditions", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClosedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClosedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DecisionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExpiresAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("GoNoGoConditions", (string)null);

                    b.HasAnnotation("Sqlite:UseSqlReturningClause", false);
                });

            modelBuilder.Entity("ReleaseMgmt.Domain.Entities.GoNoGoDecisions", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("DecidedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DecidedByUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GateSnapshotJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NewTargetReleaseDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReleaseTrainId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("GoNoGoDecisions", (string)null);

                    b.HasAnnotation("Sqlite:UseSqlReturningClause", false);
                });

            modelBuilder.Entity("ReleaseMgmt.Domain.Entities.Holidays", b =>
                {
                    b.Property<string>("Day")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Day");

                    b.ToTable("Holidays", (string)null);

                    b.HasAnnotation("Sqlite:UseSqlReturningClause", false);
                });

            modelBuilder.Entity("ReleaseMgmt.Domain.Entities.IcsTokens", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RevokedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenSha256")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("IcsTokens", (string)null);

                    b.HasAnnotation("Sqlite:UseSqlReturningClause", false);
                });

            modelBuilder.Entity("ReleaseMgmt.Domain.Entities.ImportJobs", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CommittedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ErrorCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReleaseTrainId")
                        .HasColumnType("TEXT");

                    b.Property<int>("RowCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UploadedByUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ImportJobs", (string)null);

                    b.HasAnnotation("Sqlite:UseSqlReturningClause", false);
                });

            modelBuilder.Entity("ReleaseMgmt.Domain.Entities.KnownIssues", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("RaisedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReleaseTrainId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResolvedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Workaround")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("KnownIssues", (string)null);

                    b.HasAnnotation("Sqlite:UseSqlReturningClause", false);
                });

            modelBuilder.Entity("ReleaseMgmt.Domain.Entities.MetricSnapshots", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CapturedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExportJobId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MetricKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PeriodEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("PeriodStart")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReleaseTrainId")
                        .HasColumnType("TEXT");

                    b.Property<double>("Value")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("MetricSnapshots", (string)null);

                    b.HasAnnotation("Sqlite:UseSqlReturningClause", false);
                });

            modelBuilder.Entity("ReleaseMgmt.Domain.Entities.Notifications", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EscalationLevel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReadAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Notifications", (string)null);

                    b.HasAnnotation("Sqlite:UseSqlReturningClause", false);
                });

            modelBuilder.Entity("ReleaseMgmt.Domain.Entities.ParsePreviews", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CommittedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ErrorCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExpiresAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReleaseTrainId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResultJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TrainVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ParsePreviews", (string)null);

                    b.HasAnnotation("Sqlite:UseSqlReturningClause", false);
                });

            modelBuilder.Entity("ReleaseMgmt.Domain.Entities.PirActions", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("DoneAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DueOn")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PirId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("PirActions", (string)null);

                    b.HasAnnotation("Sqlite:UseSqlReturningClause", false);
                });

            modelBuilder.Entity("ReleaseMgmt.Domain.Entities.PostImplementationReviews", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("HeldAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReleaseTrainId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RequiredReason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("PostImplementationReviews", (string)null);

                    b.HasAnnotation("Sqlite:UseSqlReturningClause", false);
                });

            modelBuilder.Entity("ReleaseMgmt.Domain.Entities.ReleaseTrains", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ActualEndAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ActualStartAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ArchivedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChangeTicketNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClonedFromTrainId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CloseCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("CloseNotes")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HypercareExitAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("HypercareExitByUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastChangedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastChangedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RiskTier")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RollbackRehearsedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RollbackRehearsedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetReleaseDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TemplateId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ReleaseTrains", (string)null);

                    b.HasAnnotation("Sqlite:UseSqlReturningClause", false);
                });

            modelBuilder.Entity("ReleaseMgmt.Domain.Entities.RunbookRuns", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("EndedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Outcome")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReleaseTrainId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StartedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StartedByUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("RunbookRuns", (string)null);

                    b.HasAnnotation("Sqlite:UseSqlReturningClause", false);
                });

            modelBuilder.Entity("ReleaseMgmt.Domain.Entities.RunbookSteps", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("BundledProductId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Instructions")
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerTeamId")
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerUserId")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlannedDurationMin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlannedStartAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReleaseTrainId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StepCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("RunbookSteps", (string)null);

                    b.HasAnnotation("Sqlite:UseSqlReturningClause", false);
                });

            modelBuilder.Entity("ReleaseMgmt.Domain.Entities.StageGates", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CertifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CertifiedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DueOn")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GateClass")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GateName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastChangedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastChangedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<int>("OffsetDays")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OwnerTeamId")
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReleaseTrainId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RequiredBeforeStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SequenceOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("StageGates", (string)null);

                    b.HasAnnotation("Sqlite:UseSqlReturningClause", false);
                });

            modelBuilder.Entity("ReleaseMgmt.Domain.Entities.StepDependencies", b =>
                {
                    b.Property<string>("StepId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DependsOnStepId")
                        .HasColumnType("TEXT");

                    b.HasKey("StepId", "DependsOnStepId");

                    b.ToTable("StepDependencies", (string)null);

                    b.HasAnnotation("Sqlite:UseSqlReturningClause", false);
                });

            modelBuilder.Entity("ReleaseMgmt.Domain.Entities.StepExecutions", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ActorUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ActualEndAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ActualStartAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<string>("RunId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StepId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("StepExecutions", (string)null);

                    b.HasAnnotation("Sqlite:UseSqlReturningClause", false);
                });

            modelBuilder.Entity("ReleaseMgmt.Domain.Entities.SyncAlerts", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstOccurredAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastOccurredAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OccurrenceCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReleaseTrainId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResolvedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResolvedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceSystem")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SyncAlerts", (string)null);

                    b.HasAnnotation("Sqlite:UseSqlReturningClause", false);
                });

            modelBuilder.Entity("ReleaseMgmt.Domain.Entities.TeamMembers", b =>
                {
                    b.Property<string>("TeamId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("TeamId", "UserId");

                    b.ToTable("TeamMembers", (string)null);

                    b.HasAnnotation("Sqlite:UseSqlReturningClause", false);
                });

            modelBuilder.Entity("ReleaseMgmt.Domain.Entities.Teams", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Handle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WebhookDestinationId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Teams", (string)null);

                    b.HasAnnotation("Sqlite:UseSqlReturningClause", false);
                });

            modelBuilder.Entity("ReleaseMgmt.Domain.Entities.TemplateCommSchedule", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("LibraryTemplateId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OffsetDays")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TemplateId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("TemplateCommSchedule", (string)null);

                    b.HasAnnotation("Sqlite:UseSqlReturningClause", false);
                });

            modelBuilder.Entity("ReleaseMgmt.Domain.Entities.TemplateGates", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("GateClass")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GateName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OffsetDays")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OwnerTeamId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequiredBeforeStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SequenceOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TemplateId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("TemplateGates", (string)null);

                    b.HasAnnotation("Sqlite:UseSqlReturningClause", false);
                });

            modelBuilder.Entity("ReleaseMgmt.Domain.Entities.TemplateSteps", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("OffsetMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OwnerTeamId")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlannedDurationMin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StepCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TemplateId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("TemplateSteps", (string)null);

                    b.HasAnnotation("Sqlite:UseSqlReturningClause", false);
                });

            modelBuilder.Entity("ReleaseMgmt.Domain.Entities.TrainTemplates", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ApprovedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ApprovedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultRiskTier")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReviewDueOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("TrainTemplates", (string)null);

                    b.HasAnnotation("Sqlite:UseSqlReturningClause", false);
                });

            modelBuilder.Entity("ReleaseMgmt.Domain.Entities.UserSessionState", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ActiveTrainId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastActivityAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UIStateJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "ClientId");

                    b.ToTable("UserSessionState", (string)null);

                    b.HasAnnotation("Sqlite:UseSqlReturningClause", false);
                });

            modelBuilder.Entity("ReleaseMgmt.Domain.Entities.Users", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Handle")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);

                    b.HasAnnotation("Sqlite:UseSqlReturningClause", false);
                });

            modelBuilder.Entity("ReleaseMgmt.Domain.Entities.WebhookDestinations", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("WebhookDestinations", (string)null);

                    b.HasAnnotation("Sqlite:UseSqlReturningClause", false);
                });
#pragma warning restore 612, 618
        }
    }
}
