// <auto-generated> by tools/gen_entities.py from db/schema.sql. Do not edit.
#nullable enable
using Microsoft.EntityFrameworkCore;
using ReleaseMgmt.Domain.Entities;

namespace ReleaseMgmt.Infrastructure.Persistence;

public static class ModelMap
{
    public static void Apply(ModelBuilder b)
    {
        b.Entity<Users>(e => { e.ToTable("Users"); e.HasKey(e => e.Id);  });
        b.Entity<Teams>(e => { e.ToTable("Teams"); e.HasKey(e => e.Id);  });
        b.Entity<TeamMembers>(e => { e.ToTable("TeamMembers"); e.HasKey(e => new { e.TeamId, e.UserId });  });
        b.Entity<Holidays>(e => { e.ToTable("Holidays"); e.HasKey(e => e.Day);  });
        b.Entity<TrainTemplates>(e => { e.ToTable("TrainTemplates"); e.HasKey(e => e.Id);  });
        b.Entity<TemplateGates>(e => { e.ToTable("TemplateGates"); e.HasKey(e => e.Id);  });
        b.Entity<TemplateSteps>(e => { e.ToTable("TemplateSteps"); e.HasKey(e => e.Id);  });
        b.Entity<TemplateCommSchedule>(e => { e.ToTable("TemplateCommSchedule"); e.HasKey(e => e.Id);  });
        b.Entity<CommTemplateLibrary>(e => { e.ToTable("CommTemplateLibrary"); e.HasKey(e => e.Id);  });
        b.Entity<ReleaseTrains>(e => { e.ToTable("ReleaseTrains"); e.HasKey(e => e.Id);  });
        b.Entity<ChangeRecords>(e => { e.ToTable("ChangeRecords"); e.HasKey(e => e.ReleaseTrainId);  });
        b.Entity<AffectedCIs>(e => { e.ToTable("AffectedCIs"); e.HasKey(e => e.Id);  });
        b.Entity<DeploymentWindows>(e => { e.ToTable("DeploymentWindows"); e.HasKey(e => e.Id);  });
        b.Entity<BundledProducts>(e => { e.ToTable("BundledProducts"); e.HasKey(e => e.Id);  });
        b.Entity<StageGates>(e => { e.ToTable("StageGates"); e.HasKey(e => e.Id);  });
        b.Entity<GateTransitions>(e => { e.ToTable("GateTransitions"); e.HasKey(e => e.Id); e.Property(e => e.Id).ValueGeneratedOnAdd(); });
        b.Entity<GateWaivers>(e => { e.ToTable("GateWaivers"); e.HasKey(e => e.Id);  });
        b.Entity<ChecklistTasks>(e => { e.ToTable("ChecklistTasks"); e.HasKey(e => e.Id);  });
        b.Entity<Attachments>(e => { e.ToTable("Attachments"); e.HasKey(e => e.Id);  });
        b.Entity<RunbookSteps>(e => { e.ToTable("RunbookSteps"); e.HasKey(e => e.Id);  });
        b.Entity<StepDependencies>(e => { e.ToTable("StepDependencies"); e.HasKey(e => new { e.StepId, e.DependsOnStepId });  });
        b.Entity<RunbookRuns>(e => { e.ToTable("RunbookRuns"); e.HasKey(e => e.Id);  });
        b.Entity<StepExecutions>(e => { e.ToTable("StepExecutions"); e.HasKey(e => e.Id);  });
        b.Entity<Blockers>(e => { e.ToTable("Blockers"); e.HasKey(e => e.Id);  });
        b.Entity<KnownIssues>(e => { e.ToTable("KnownIssues"); e.HasKey(e => e.Id);  });
        b.Entity<GoNoGoDecisions>(e => { e.ToTable("GoNoGoDecisions"); e.HasKey(e => e.Id);  });
        b.Entity<GoNoGoConditions>(e => { e.ToTable("GoNoGoConditions"); e.HasKey(e => e.Id);  });
        b.Entity<PostImplementationReviews>(e => { e.ToTable("PostImplementationReviews"); e.HasKey(e => e.Id);  });
        b.Entity<PirActions>(e => { e.ToTable("PirActions"); e.HasKey(e => e.Id);  });
        b.Entity<FreezeWindows>(e => { e.ToTable("FreezeWindows"); e.HasKey(e => e.Id);  });
        b.Entity<FreezeOverrides>(e => { e.ToTable("FreezeOverrides"); e.HasKey(e => e.Id);  });
        b.Entity<Baselines>(e => { e.ToTable("Baselines"); e.HasKey(e => e.Id);  });
        b.Entity<ExternalLinks>(e => { e.ToTable("ExternalLinks"); e.HasKey(e => e.Id);  });
        b.Entity<SyncAlerts>(e => { e.ToTable("SyncAlerts"); e.HasKey(e => e.Id);  });
        b.Entity<WebhookDestinations>(e => { e.ToTable("WebhookDestinations"); e.HasKey(e => e.Id);  });
        b.Entity<CommTemplates>(e => { e.ToTable("CommTemplates"); e.HasKey(e => e.Id);  });
        b.Entity<CommSchedule>(e => { e.ToTable("CommSchedule"); e.HasKey(e => e.Id);  });
        b.Entity<CommDispatches>(e => { e.ToTable("CommDispatches"); e.HasKey(e => e.Id);  });
        b.Entity<Notifications>(e => { e.ToTable("Notifications"); e.HasKey(e => e.Id);  });
        b.Entity<UserSessionState>(e => { e.ToTable("UserSessionState"); e.HasKey(e => new { e.UserId, e.ClientId });  });
        b.Entity<ImportJobs>(e => { e.ToTable("ImportJobs"); e.HasKey(e => e.Id);  });
        b.Entity<ExportJobs>(e => { e.ToTable("ExportJobs"); e.HasKey(e => e.Id);  });
        b.Entity<MetricSnapshots>(e => { e.ToTable("MetricSnapshots"); e.HasKey(e => e.Id); e.Property(e => e.Id).ValueGeneratedOnAdd(); });
        b.Entity<IcsTokens>(e => { e.ToTable("IcsTokens"); e.HasKey(e => e.Id);  });
        b.Entity<ParsePreviews>(e => { e.ToTable("ParsePreviews"); e.HasKey(e => e.Id);  });
        b.Entity<ConnectorState>(e => { e.ToTable("ConnectorState"); e.HasKey(e => e.SourceSystem);  });
        b.Entity<AuditEvents>(e => { e.ToTable("AuditEvents"); e.HasKey(e => e.Id); e.Property(e => e.Id).ValueGeneratedOnAdd(); });
    }
}
