#!/usr/bin/env python3
"""Generates Domain entities and the Infrastructure model map from db/schema.sql.

db/schema.sql stays the contract; rerun after a schema change:  python3 tools/gen_entities.py
Outputs:
  src/ReleaseMgmt.Domain/Entities/Entities.g.cs          POCOs, no EF references
  src/ReleaseMgmt.Infrastructure/Persistence/ModelMap.g.cs  keys, table names, generated-on-add flags
"""
import re, sys, pathlib

root = pathlib.Path(__file__).resolve().parent.parent
sql = (root / "db/schema.sql").read_text()

# Columns whose TEXT holds a calendar date (YYYY-MM-DD) rather than a UTC timestamp.
DATE_SUFFIXES = ("On", "Date")
DATE_EXACT = {"Day", "TargetReleaseDate", "CabDate", "ReviewDueOn", "DueOn", "PlannedReleaseDate", "NewTargetReleaseDate", "PeriodStart", "PeriodEnd"}
# Columns that are timestamps although they do not end in "At".
TIMESTAMP_EXACT = set()

def strip_comments(s):
    return re.sub(r"--[^\n]*", "", s)

def split_top(body):
    parts, depth, cur = [], 0, ""
    for ch in body:
        if ch == "(": depth += 1
        if ch == ")": depth -= 1
        if ch == "," and depth == 0:
            parts.append(cur.strip()); cur = ""
        else:
            cur += ch
    if cur.strip(): parts.append(cur.strip())
    return parts

tables = []
for m in re.finditer(r"CREATE TABLE (\w+) \((.*?)\n\);", strip_comments(sql), re.S):
    name, body = m.group(1), m.group(2)
    cols, pk = [], []
    for part in split_top(body):
        part = " ".join(part.split())
        head = part.split(" ")[0].upper()
        if head == "PRIMARY":
            pk = [c.strip() for c in re.search(r"\((.*)\)", part).group(1).split(",")]
            continue
        if head in ("UNIQUE", "CHECK", "FOREIGN", "CONSTRAINT"):
            continue
        cm = re.match(r"(\w+) (TEXT|INTEGER|REAL)\b(.*)", part)
        cols.append(dict(name=cm.group(1), sql=cm.group(2), rest=cm.group(3)))
    tables.append((name, cols, pk))

def cs_type(t, c):
    n, rest = c["name"], c["rest"]
    nullable = "NOT NULL" not in rest and "PRIMARY KEY" not in rest
    if c["sql"] == "REAL": base = "double"
    elif c["sql"] == "INTEGER":
        if re.search(r"CHECK \(\w+ IN \(0,\s*1\)\)", rest): base = "bool"
        elif "PRIMARY KEY" in rest or n.endswith(("Bytes", "Size")) or n == "Id": base = "long"
        else: base = "int"
    else:
        if n in DATE_EXACT or n.endswith(DATE_SUFFIXES): base = "DateOnly"
        elif n.endswith("At") or n in TIMESTAMP_EXACT: base = "DateTime"
        else: base = "string"
    if base == "string":
        return "string?" if nullable else "string"
    return base + ("?" if nullable else "")

ent, mm, fks = [], [], []
for name, cols, pk in tables:
    if not pk:
        pk = [c["name"] for c in cols if "PRIMARY KEY" in c["rest"]]
    autoinc = any("AUTOINCREMENT" in c["rest"] for c in cols)
    lines = [f"public class {name}", "{"]
    for c in cols:
        t = cs_type(name, c)
        default = ' = "";' if t == "string" else ""
        dm = re.search(r"DEFAULT (?:'([^']*)'|(-?\d+(?:\.\d+)?))", c["rest"])   # mirror the column's DEFAULT so new rows pass the CHECKs
        if dm and t.rstrip("?") == "string": default = f' = "{dm.group(1)}";'
        elif dm and dm.group(2) is not None and t.rstrip("?") in ("int", "long", "double"): default = f" = {dm.group(2)};"
        elif dm and dm.group(2) is not None and t.rstrip("?") == "bool": default = f" = {'true' if dm.group(2) == '1' else 'false'};"
        if t == "string" and c["name"] == "Id": default = " = Ids.New();"
        lines.append(f"    public {t} {c['name']} {{ get; set; }}{default}")
    lines.append("}")
    ent.append("\n".join(lines))
    for c in cols:
        r = re.search(r"REFERENCES (\w+)\((\w+)\)", c["rest"])
        if r:
            # Ordering metadata only: DDL comes from schema.sql. NoAction so EF never emulates the database's cascades.
            fks.append(f'        b.Entity<{name}>().HasOne<{r.group(1)}>().WithMany().HasForeignKey(e => e.{c["name"]}).HasPrincipalKey(p => p.{r.group(2)}).OnDelete(DeleteBehavior.NoAction);')
    keyexpr = f"e.{pk[0]}" if len(pk) == 1 else "new { " + ", ".join(f"e.{k}" for k in pk) + " }"
    extra = ".ValueGeneratedOnAdd()" if autoinc else ""
    mm.append(f'        b.Entity<{name}>(e => {{ e.ToTable("{name}"); e.HasKey(e => {keyexpr}); {"e.Property(e => e.Id).ValueGeneratedOnAdd();" if autoinc else ""} }});')

out = root / "src/ReleaseMgmt.Domain/Entities"; out.mkdir(parents=True, exist_ok=True)
(out / "Entities.g.cs").write_text(
    "// <auto-generated> by tools/gen_entities.py from db/schema.sql. Do not edit.\n#nullable enable\n"
    "using ReleaseMgmt.Domain.Common;\n\nnamespace ReleaseMgmt.Domain.Entities;\n\n" + "\n\n".join(ent) + "\n")
(root / "src/ReleaseMgmt.Infrastructure/Persistence/ModelMap.g.cs").write_text(
    "// <auto-generated> by tools/gen_entities.py from db/schema.sql. Do not edit.\n#nullable enable\n"
    "using Microsoft.EntityFrameworkCore;\nusing ReleaseMgmt.Domain.Entities;\n\nnamespace ReleaseMgmt.Infrastructure.Persistence;\n\n"
    "public static class ModelMap\n{\n    public static void Apply(ModelBuilder b)\n    {\n" + "\n".join(mm) + "\n\n        // Foreign keys (from REFERENCES): let EF order dependent inserts and deletes\n" + "\n".join(fks) + "\n    }\n}\n")
print(f"{len(tables)} tables")
if "--report" in sys.argv:
    for name, cols, pk in tables:
        for c in cols:
            if cs_type(name, c).rstrip("?") == "string" and re.search(r"(Start|End|Until|From|Time|Expires|Due|Date|Day|On)$", c["name"]):
                print("check:", name, c["name"], c["rest"][:50])
