// <auto-generated> by tools/gen_entities.py from db/schema.sql. Do not edit.
#nullable enable
using ReleaseMgmt.Domain.Common;

namespace ReleaseMgmt.Domain.Entities;

public class Users
{
    public string Id { get; set; } = Ids.New();
    public string Email { get; set; } = "";
    public string DisplayName { get; set; } = "";
    public string Role { get; set; } = "";
    public string? Handle { get; set; }
    public bool IsActive { get; set; }
    public int Version { get; set; } = 1;
}

public class Teams
{
    public string Id { get; set; } = Ids.New();
    public string Handle { get; set; } = "";
    public string Name { get; set; } = "";
    public string? WebhookDestinationId { get; set; }
    public int Version { get; set; } = 1;
}

public class TeamMembers
{
    public string TeamId { get; set; } = "";
    public string UserId { get; set; } = "";
}

public class Holidays
{
    public DateOnly Day { get; set; }
    public string Name { get; set; } = "";
    public int Version { get; set; } = 1;
}

public class TrainTemplates
{
    public string Id { get; set; } = Ids.New();
    public string Name { get; set; } = "";
    public string Status { get; set; } = "";
    public string DefaultRiskTier { get; set; } = "";
    public string? ApprovedByUserId { get; set; }
    public DateTime? ApprovedAt { get; set; }
    public DateOnly? ReviewDueOn { get; set; }
    public int Version { get; set; } = 1;
}

public class TemplateGates
{
    public string Id { get; set; } = Ids.New();
    public string TemplateId { get; set; } = "";
    public string GateName { get; set; } = "";
    public string GateClass { get; set; } = "";
    public int SequenceOrder { get; set; }
    public int OffsetDays { get; set; }
    public string RequiredBeforeStatus { get; set; } = "";
    public string? OwnerTeamId { get; set; }
    public int Version { get; set; } = 1;
}

public class TemplateSteps
{
    public string Id { get; set; } = Ids.New();
    public string TemplateId { get; set; } = "";
    public string StepCode { get; set; } = "";
    public string Section { get; set; } = "";
    public string Title { get; set; } = "";
    public int OffsetMinutes { get; set; }
    public int PlannedDurationMin { get; set; }
    public string? OwnerTeamId { get; set; }
    public int Version { get; set; } = 1;
}

public class TemplateCommSchedule
{
    public string Id { get; set; } = Ids.New();
    public string TemplateId { get; set; } = "";
    public string LibraryTemplateId { get; set; } = "";
    public int OffsetDays { get; set; }
    public int Version { get; set; } = 1;
}

public class CommTemplateLibrary
{
    public string Id { get; set; } = Ids.New();
    public string TemplateType { get; set; } = "";
    public string Name { get; set; } = "";
    public string Audience { get; set; } = "";
    public string SubjectLine { get; set; } = "";
    public string MarkdownBody { get; set; } = "";
    public int Version { get; set; } = 1;
}

public class ReleaseTrains
{
    public string Id { get; set; } = Ids.New();
    public string Title { get; set; } = "";
    public string? TemplateId { get; set; }
    public string? ClonedFromTrainId { get; set; }
    public DateOnly TargetReleaseDate { get; set; }
    public string RiskTier { get; set; } = "";
    public string CurrentStatus { get; set; } = "";
    public string? ChangeTicketNumber { get; set; }
    public DateTime? ActualStartAt { get; set; }
    public DateTime? ActualEndAt { get; set; }
    public string? CloseCode { get; set; }
    public string? CloseNotes { get; set; }
    public DateTime? RollbackRehearsedAt { get; set; }
    public string? RollbackRehearsedByUserId { get; set; }
    public DateTime? HypercareExitAt { get; set; }
    public string? HypercareExitByUserId { get; set; }
    public DateTime? ArchivedAt { get; set; }
    public string? LastChangedByUserId { get; set; }
    public DateTime? LastChangedAt { get; set; }
    public int Version { get; set; } = 1;
    public DateTime CreatedAt { get; set; }
    public DateTime UpdatedAt { get; set; }
}

public class ChangeRecords
{
    public string ReleaseTrainId { get; set; } = "";
    public string? Justification { get; set; }
    public string? ImplementationPlan { get; set; }
    public string? RiskImpactAnalysis { get; set; }
    public string? BackoutPlan { get; set; }
    public string? TestPlan { get; set; }
    public string? CommunicationPlan { get; set; }
    public DateOnly? CabDate { get; set; }
    public int Version { get; set; } = 1;
}

public class AffectedCIs
{
    public string Id { get; set; } = Ids.New();
    public string ReleaseTrainId { get; set; } = "";
    public string CiName { get; set; } = "";
    public string? CiExternalId { get; set; }
    public int Version { get; set; } = 1;
}

public class DeploymentWindows
{
    public string Id { get; set; } = Ids.New();
    public string ReleaseTrainId { get; set; } = "";
    public DateTime StartsAt { get; set; }
    public DateTime EndsAt { get; set; }
    public int Version { get; set; } = 1;
}

public class BundledProducts
{
    public string Id { get; set; } = Ids.New();
    public string ReleaseTrainId { get; set; } = "";
    public string ProductName { get; set; } = "";
    public string VersionTag { get; set; } = "";
    public string ProjectCode { get; set; } = "";
    public int Version { get; set; } = 1;
}

public class StageGates
{
    public string Id { get; set; } = Ids.New();
    public string ReleaseTrainId { get; set; } = "";
    public string GateName { get; set; } = "";
    public string GateClass { get; set; } = "";
    public int SequenceOrder { get; set; }
    public int OffsetDays { get; set; }
    public DateOnly DueOn { get; set; }
    public string RequiredBeforeStatus { get; set; } = "";
    public string? OwnerUserId { get; set; }
    public string? OwnerTeamId { get; set; }
    public string Status { get; set; } = "";
    public string? CertifiedByUserId { get; set; }
    public DateTime? CertifiedAt { get; set; }
    public string? LastChangedByUserId { get; set; }
    public DateTime? LastChangedAt { get; set; }
    public int Version { get; set; } = 1;
}

public class GateTransitions
{
    public long Id { get; set; }
    public string StageGateId { get; set; } = "";
    public string FromStatus { get; set; } = "";
    public string ToStatus { get; set; } = "";
    public string? ActorUserId { get; set; }
    public DateTime OccurredAt { get; set; }
}

public class GateWaivers
{
    public string Id { get; set; } = Ids.New();
    public string StageGateId { get; set; } = "";
    public string Reason { get; set; } = "";
    public string RequestedByUserId { get; set; } = "";
    public string? ApprovedByUserId { get; set; }
    public DateTime RequestedAt { get; set; }
    public DateTime? ApprovedAt { get; set; }
    public int Version { get; set; } = 1;
}

public class ChecklistTasks
{
    public string Id { get; set; } = Ids.New();
    public string StageGateId { get; set; } = "";
    public string? BundledProductId { get; set; }
    public string TaskDescription { get; set; } = "";
    public string? OwnerUserId { get; set; }
    public string? OwnerTeamId { get; set; }
    public bool IsCompleted { get; set; }
    public int SequenceOrder { get; set; }
    public DateTime? CompletedAt { get; set; }
    public string? CompletedByUserId { get; set; }
    public string? LastChangedByUserId { get; set; }
    public DateTime? LastChangedAt { get; set; }
    public int Version { get; set; } = 1;
}

public class Attachments
{
    public string Id { get; set; } = Ids.New();
    public string ReleaseTrainId { get; set; } = "";
    public string EntityType { get; set; } = "";
    public string EntityId { get; set; } = "";
    public string FileName { get; set; } = "";
    public string ContentType { get; set; } = "";
    public long SizeBytes { get; set; }
    public string Sha256 { get; set; } = "";
    public string StoragePath { get; set; } = "";
    public string UploadedByUserId { get; set; } = "";
    public DateTime UploadedAt { get; set; }
    public bool IsLocked { get; set; }
}

public class RunbookSteps
{
    public string Id { get; set; } = Ids.New();
    public string ReleaseTrainId { get; set; } = "";
    public string? BundledProductId { get; set; }
    public string StepCode { get; set; } = "";
    public string Section { get; set; } = "";
    public string Title { get; set; } = "";
    public string? Instructions { get; set; }
    public string? OwnerUserId { get; set; }
    public string? OwnerTeamId { get; set; }
    public DateTime PlannedStartAt { get; set; }
    public int PlannedDurationMin { get; set; }
    public int Version { get; set; } = 1;
}

public class StepDependencies
{
    public string StepId { get; set; } = "";
    public string DependsOnStepId { get; set; } = "";
}

public class RunbookRuns
{
    public string Id { get; set; } = Ids.New();
    public string ReleaseTrainId { get; set; } = "";
    public string Mode { get; set; } = "";
    public DateTime StartedAt { get; set; }
    public string StartedByUserId { get; set; } = "";
    public DateTime? EndedAt { get; set; }
    public string? Outcome { get; set; }
    public int Version { get; set; } = 1;
}

public class StepExecutions
{
    public string Id { get; set; } = Ids.New();
    public string RunId { get; set; } = "";
    public string StepId { get; set; } = "";
    public string Status { get; set; } = "";
    public DateTime? ActualStartAt { get; set; }
    public DateTime? ActualEndAt { get; set; }
    public string? ActorUserId { get; set; }
    public string? Note { get; set; }
    public int Version { get; set; } = 1;
}

public class Blockers
{
    public string Id { get; set; } = Ids.New();
    public string ReleaseTrainId { get; set; } = "";
    public string? BundledProductId { get; set; }
    public string? StageGateId { get; set; }
    public string Title { get; set; } = "";
    public string Severity { get; set; } = "";
    public string? OwnerUserId { get; set; }
    public DateTime RaisedAt { get; set; }
    public DateTime? ResolvedAt { get; set; }
    public int Version { get; set; } = 1;
}

public class KnownIssues
{
    public string Id { get; set; } = Ids.New();
    public string ReleaseTrainId { get; set; } = "";
    public string Title { get; set; } = "";
    public string Severity { get; set; } = "";
    public string? Workaround { get; set; }
    public string Status { get; set; } = "";
    public string? ExternalKey { get; set; }
    public DateTime RaisedAt { get; set; }
    public DateTime? ResolvedAt { get; set; }
    public int Version { get; set; } = 1;
}

public class GoNoGoDecisions
{
    public string Id { get; set; } = Ids.New();
    public string ReleaseTrainId { get; set; } = "";
    public string Decision { get; set; } = "";
    public string DecidedByUserId { get; set; } = "";
    public DateTime DecidedAt { get; set; }
    public string GateSnapshotJson { get; set; } = "";
    public string? Notes { get; set; }
    public DateOnly? NewTargetReleaseDate { get; set; }
}

public class GoNoGoConditions
{
    public string Id { get; set; } = Ids.New();
    public string DecisionId { get; set; } = "";
    public string Text { get; set; } = "";
    public string OwnerUserId { get; set; } = "";
    public DateTime ExpiresAt { get; set; }
    public DateTime? ClosedAt { get; set; }
    public string? ClosedByUserId { get; set; }
    public int Version { get; set; } = 1;
}

public class PostImplementationReviews
{
    public string Id { get; set; } = Ids.New();
    public string ReleaseTrainId { get; set; } = "";
    public string RequiredReason { get; set; } = "";
    public string Status { get; set; } = "";
    public DateTime? HeldAt { get; set; }
    public string? Summary { get; set; }
    public int Version { get; set; } = 1;
}

public class PirActions
{
    public string Id { get; set; } = Ids.New();
    public string PirId { get; set; } = "";
    public string Text { get; set; } = "";
    public string OwnerUserId { get; set; } = "";
    public DateOnly DueOn { get; set; }
    public DateTime? DoneAt { get; set; }
    public int Version { get; set; } = 1;
}

public class FreezeWindows
{
    public string Id { get; set; } = Ids.New();
    public string Name { get; set; } = "";
    public string Kind { get; set; } = "";
    public DateTime StartsAt { get; set; }
    public DateTime EndsAt { get; set; }
    public string? ProductPattern { get; set; }
    public string CreatedByUserId { get; set; } = "";
    public int Version { get; set; } = 1;
}

public class FreezeOverrides
{
    public string Id { get; set; } = Ids.New();
    public string FreezeWindowId { get; set; } = "";
    public string ReleaseTrainId { get; set; } = "";
    public string Reason { get; set; } = "";
    public string RequestedByUserId { get; set; } = "";
    public string ApprovedByUserId { get; set; } = "";
    public DateTime ApprovedAt { get; set; }
    public DateTime ExpiresAt { get; set; }
}

public class Baselines
{
    public string Id { get; set; } = Ids.New();
    public string ReleaseTrainId { get; set; } = "";
    public DateTime CapturedAt { get; set; }
    public string? CapturedAtGateId { get; set; }
    public DateOnly PlannedReleaseDate { get; set; }
    public string SnapshotJson { get; set; } = "";
    public string? CapturedByUserId { get; set; }
}

public class ExternalLinks
{
    public string Id { get; set; } = Ids.New();
    public string ReleaseTrainId { get; set; } = "";
    public string EntityType { get; set; } = "";
    public string EntityId { get; set; } = "";
    public string SourceSystem { get; set; } = "";
    public string ExternalKey { get; set; } = "";
    public string? ExpectedStatus { get; set; }
    public string? LastSyncedStatus { get; set; }
    public DateTime? LastSyncedAt { get; set; }
    public string SyncState { get; set; } = "";
    public int Version { get; set; } = 1;
}

public class SyncAlerts
{
    public string Id { get; set; } = Ids.New();
    public string? ReleaseTrainId { get; set; }
    public string SourceSystem { get; set; } = "";
    public string Kind { get; set; } = "";
    public string Fingerprint { get; set; } = "";
    public string ErrorMessage { get; set; } = "";
    public int OccurrenceCount { get; set; }
    public DateTime FirstOccurredAt { get; set; }
    public DateTime LastOccurredAt { get; set; }
    public bool IsResolved { get; set; }
    public DateTime? ResolvedAt { get; set; }
    public string? ResolvedByUserId { get; set; }
    public int Version { get; set; } = 1;
}

public class WebhookDestinations
{
    public string Id { get; set; } = Ids.New();
    public string Name { get; set; } = "";
    public string Url { get; set; } = "";
    public string Kind { get; set; } = "";
    public int Version { get; set; } = 1;
}

public class CommTemplates
{
    public string Id { get; set; } = Ids.New();
    public string ReleaseTrainId { get; set; } = "";
    public string? LibraryTemplateId { get; set; }
    public string? StageGateId { get; set; }
    public string TemplateType { get; set; } = "";
    public string Audience { get; set; } = "";
    public string SubjectLine { get; set; } = "";
    public string MarkdownBody { get; set; } = "";
    public int Version { get; set; } = 1;
}

public class CommSchedule
{
    public string Id { get; set; } = Ids.New();
    public string ReleaseTrainId { get; set; } = "";
    public string CommTemplateId { get; set; } = "";
    public DateTime DueAt { get; set; }
    public DateTime? SentAt { get; set; }
    public string? DispatchId { get; set; }
    public int Version { get; set; } = 1;
}

public class CommDispatches
{
    public string Id { get; set; } = Ids.New();
    public string CommTemplateId { get; set; } = "";
    public string Channel { get; set; } = "";
    public string? WebhookDestinationId { get; set; }
    public string HydratedSubject { get; set; } = "";
    public string HydratedBody { get; set; } = "";
    public string DispatchedByUserId { get; set; } = "";
    public DateTime DispatchedAt { get; set; }
    public bool IsRehearsal { get; set; }
    public string Outcome { get; set; } = "";
}

public class Notifications
{
    public string Id { get; set; } = Ids.New();
    public string UserId { get; set; } = "";
    public string Kind { get; set; } = "";
    public string EntityType { get; set; } = "";
    public string EntityId { get; set; } = "";
    public int EscalationLevel { get; set; }
    public string Message { get; set; } = "";
    public DateTime CreatedAt { get; set; }
    public DateTime? ReadAt { get; set; }
    public int Version { get; set; } = 1;
}

public class UserSessionState
{
    public string UserId { get; set; } = "";
    public string ClientId { get; set; } = "";
    public string? ActiveTrainId { get; set; }
    public int SchemaVersion { get; set; }
    public string UIStateJson { get; set; } = "";
    public DateTime LastActivityAt { get; set; }
}

public class ImportJobs
{
    public string Id { get; set; } = Ids.New();
    public string Kind { get; set; } = "";
    public string? ReleaseTrainId { get; set; }
    public string FileName { get; set; } = "";
    public string Sha256 { get; set; } = "";
    public int RowCount { get; set; }
    public int ErrorCount { get; set; }
    public string ErrorsJson { get; set; } = "";
    public string Status { get; set; } = "";
    public string UploadedByUserId { get; set; } = "";
    public DateTime CreatedAt { get; set; }
    public DateTime? CommittedAt { get; set; }
    public int Version { get; set; } = 1;
}

public class ExportJobs
{
    public string Id { get; set; } = Ids.New();
    public string Kind { get; set; } = "";
    public string? ReleaseTrainId { get; set; }
    public string Parameters { get; set; } = "";
    public string FileName { get; set; } = "";
    public string? Sha256 { get; set; }
    public string? StoragePath { get; set; }
    public string RequestedByUserId { get; set; } = "";
    public DateTime CreatedAt { get; set; }
    public DateTime? CompletedAt { get; set; }
    public string Status { get; set; } = "";
    public int Version { get; set; } = 1;
}

public class MetricSnapshots
{
    public long Id { get; set; }
    public string ExportJobId { get; set; } = "";
    public string? ReleaseTrainId { get; set; }
    public string MetricKey { get; set; } = "";
    public double Value { get; set; }
    public DateOnly? PeriodStart { get; set; }
    public DateOnly? PeriodEnd { get; set; }
    public DateTime CapturedAt { get; set; }
}

public class IcsTokens
{
    public string Id { get; set; } = Ids.New();
    public string UserId { get; set; } = "";
    public string TokenSha256 { get; set; } = "";
    public DateTime CreatedAt { get; set; }
    public DateTime? RevokedAt { get; set; }
}

public class ParsePreviews
{
    public string Id { get; set; } = Ids.New();
    public string ReleaseTrainId { get; set; } = "";
    public string UserId { get; set; } = "";
    public int TrainVersion { get; set; }
    public string ResultJson { get; set; } = "";
    public int ErrorCount { get; set; }
    public DateTime CreatedAt { get; set; }
    public DateTime ExpiresAt { get; set; }
    public DateTime? CommittedAt { get; set; }
}

public class ConnectorState
{
    public string SourceSystem { get; set; } = "";
    public string BaseUrl { get; set; } = "";
    public bool IsEnabled { get; set; }
    public DateTime? LastCycleStartedAt { get; set; }
    public DateTime? LastCycleCompletedAt { get; set; }
    public DateTime? LastSuccessAt { get; set; }
    public int ConsecutiveFailures { get; set; }
    public int Version { get; set; } = 1;
}

public class AuditEvents
{
    public long Id { get; set; }
    public DateTime OccurredAt { get; set; }
    public string? ActorUserId { get; set; }
    public string? ReleaseTrainId { get; set; }
    public string EntityType { get; set; } = "";
    public string EntityId { get; set; } = "";
    public string Action { get; set; } = "";
    public string? BeforeJson { get; set; }
    public string? AfterJson { get; set; }
}
